name: Update README

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install markscribe
        run: go install github.com/taciturnaxolotl/markscribe@latest

      - name: Generate README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_URL: https://hackatime.hackclub.com/api/v1/
        run: markscribe -write README.md templates/README.md.tpl

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update README"
          branch: main
